In [1]:

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpose = matrix.T
print("\nTransposed Matrix:")
print(transpose)




Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 9, 4],
    [8, 2, 1]
])
result = A + B
print("\nSum of A and B:")
print(result)



Sum of A and B:
[[ 8 11  7]
 [12  7  7]]


In [8]:
a = np.arange(0,18)
print(a)
a= a.reshape((6,3))
a
b= np.arange(20,38)
print(b)
b= b.reshape((6,3))
b 
result = a + b
print("\nSum of a and b:")
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Sum of a and b:
[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
