In [1]:

import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpose = matrix.T
print("\nTransposed Matrix:")
print(transpose)




Transposed Matrix:
[[1 4]
 [2 5]
 [3 6]]


In [2]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 9, 4],
    [8, 2, 1]
])
result = A + B
print("\nSum of A and B:")
print(result)



Sum of A and B:
[[ 8 11  7]
 [12  7  7]]
